### ISSUE TITLE
Error: could not find MySQL driver (org.gjt.mm.mysql.Driver)

### ISSUE THREAD

**Issue by x1yy** [apertium/apertium-dixtools#4]
when i run
```
java -cp .:lib/mysql-connector-java-5.1.49-bin.jar -jar dist/apertium-dixtools.jar get-bil-omegawiki id en apertium-id-en.dix
```
it always failed with message

Error: could not find MySQL driver (org.gjt.mm.mysql.Driver)

**Comment by nordfalk** [comment]
Try with:

java -cp lib/mysql-connector-java-5.1.49-bin.jar:dist/apertium-dixtools.jar ProcessDics get-bil-omegawiki id en apertium-id-en.dix

Pro problem is that -jar and -cp doesent work togehter (https://stackoverflow.com/questions/11922681/differences-between-java-cp-and-java-jar/11922724)

**Comment by fatkab** [comment]
Hi is this a channel where I can seek help, thank you!
