### ISSUE TITLE
format deletes alt in pardef

### ISSUE THREAD

**Issue by hectoralos** [apertium/apertium-dixtools#7]
I do:
`~/apertium/apertium-dixtools/apertium-dixtools format -alignMonodix apertium-oci.oci.metadix new.metadix`

Then:
`  <pardef n="S__cantar" alt="oci@aran">
`
becomes
`<pardef n="S__cantar">
`

**Comment by TinoDidriksen** [comment]
Duplicate of https://github.com/apertium/apertium-dixtools/issues/1
